using Microsoft.AspNetCore.Mvc;

namespace Hermes.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class UnprocessableMessageController : ControllerBase
    {
        private readonly UnprocessableMessageQueue _unprocessableMessageQueue;

        public UnprocessableMessageController(UnprocessableMessageQueue unprocessableMessageQueue)
        {
            _unprocessableMessageQueue = unprocessableMessageQueue;
        }

        /// <summary>
        /// Get latest unprocessable messages
        /// </summary>
        /// <returns></returns>
        [HttpGet("GetLatestUnprocessable")]
        public ActionResult GetLatestUnprocessableMessages()
        {
            return Ok(_unprocessableMessageQueue.GetLatestUnprocessableMessages());
        }

        /// <summary>
        /// Delete an unprocessable message by key
        /// </summary>
        /// <param name="key">The key value is generated by SHA256 hashing based on the values of message ConsumerTag|message DeliveryTag|message Redelivered|message Exchange|message RoutingKey</param>
        /// <returns></returns>
        [HttpDelete("Delete/{key}")]
        public ActionResult DeleteLatestUnprocessableMessage(string key)
        {
            if (_unprocessableMessageQueue.DeleteLatestUnprocessableMessage(key))
            {
                return Ok();
            }
            else
            {
                return NotFound();
            }
        }
    }
}
